### ISSUE TITLE
Resolve insecure page request for /frame

### ISSUE THREAD

**Issue by adamzerella** [govau/chameleon#23]
When deployed to our cloud environemnt the `http://localhost/frame` resource won't load due to HTTPS restrictions.

![image](https://user-images.githubusercontent.com/1501560/48928006-1c2cce80-ef2f-11e8-9305-273579612d3f.png)

**Comment by adamzerella** [comment]
We need to read in the correct `${PORT}` value client-side, the port is not `3000` when deployed.

Issue is located here:

![image](https://user-images.githubusercontent.com/1501560/48928078-b725a880-ef2f-11e8-972d-01baea6c410d.png)

**Comment by alex-page** [comment]
This is kind of interesting, because I never assumed we would host this interface on cloud. What I would do in this situation is change my local `index.html` interface with form and iframe to point the url to the cloud environment.

We do this when testing furnace as well. It is quite useful. Let me know what you think?

**Comment by adamzerella** [comment]
^ Removed `index.html` from deployment.

**Comment by alex-page** [comment]
I would close this as it is no longer an issue. You can write docs on hitting the URL with curl.
